### PR TITLE
Export DirectPV client and admin API package

### PR DESCRIPTION
**Pull request by Praveenrajmani**
This will be used to integrate DirectPV externally and provides common usage of functions

For example,

```go
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/minio/directpv/pkg/client"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

const (
	MaxThreadCount = 200
)

func getKubeConfig() (*rest.Config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	kubeConfig := filepath.Join(home, ".kube", "config")
	config, err := clientcmd.BuildConfigFromFlags("", kubeConfig)
	if err != nil {
		if config, err = rest.InClusterConfig(); err != nil {
			return nil, err
		}
	}
	config.QPS = float32(MaxThreadCount / 2)
	config.Burst = MaxThreadCount
	return config, nil
}

func main() {
	kubeConfig, err := getKubeConfig()
	if err != nil {
		fmt.Printf("%s: Could not connect to kubernetes. %s=%s\n", "Error", "KUBECONFIG", kubeConfig)
		os.Exit(1)
	}
	adminClient, err := admin.NewClient(kubeConfig)
	if err != nil {
		log.Fatalf("unable to initialize client; %v", err)
	}
	drives, err := adminClient.NewDriveLister().Get(context.Background())
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for _, drive := range drives {
		fmt.Printf("\n DeviceName: %v", drive.GetDriveName())
		fmt.Printf("\n Node: %v", drive.GetNodeID())
		fmt.Printf("\n Make: %v", drive.Status.Make)
		fmt.Println()
	}
}

```

and with the following line in go.mod

```go
replace github.com/minio/directpv => ../directpv
```

after merging, we can use the master's commit id in the go.mod

```
require (
    github.com/minio/directpv <commit-id>
)
```

also checkout the examples in `pkg/admin/examples/`

### CODE REVIEW

**Review by prakashsvmx — DISMISSED** [review]

**Review by dvaldivia — APPROVED** [review]
LGTM

**Comment by Praveenrajmani** [comment]
PTAL @prakashsvmx @balamurugana @dvaldivia

**Review by prakashsvmx — APPROVED** [review]
Tested the basic functions. LGTM :+1:

**Comment by Praveenrajmani** [comment]
Have made some changes to add appropriate return types for the admin functions. PTAL @balamurugana @prakashsvmx @dvaldivia

**Review by prakashsvmx — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
PTAL @balamurugana

**Review by balamurugana — APPROVED** [review]

**Review by prakashsvmx — APPROVED** [review]

**Pull request merged**
