### PR TITLE
Export the dynamic clients for external integrations

### PR DESCRIPTION
**Pull request by Praveenrajmani**
The dynamic client interfaces are exported for console and minio-operator to use the unversioned APIs

### CODE REVIEW

**Review by sinhaashish — DISMISSED** [review]

**Comment by Praveenrajmani** [comment]
Let me write a small program to test this. Lets not merge it without the test

**Comment by Praveenrajmani** [comment]
the following script can be used for testing

```go
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	directcsiclient "github.com/minio/directpv/pkg/client"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

const (
	MaxThreadCount = 200
)

func getKubeConfig() (*rest.Config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	kubeConfig := filepath.Join(home, ".kube", "config")
	config, err := clientcmd.BuildConfigFromFlags("", kubeConfig)
	if err != nil {
		if config, err = rest.InClusterConfig(); err != nil {
			return nil, err
		}
	}
	config.QPS = float32(MaxThreadCount / 2)
	config.Burst = MaxThreadCount
	return config, nil
}

func main() {
	kubeConfig, err := getKubeConfig()
	if err != nil {
		fmt.Printf("%s: Could not connect to kubernetes. %s=%s\n", "Error", "KUBECONFIG", kubeConfig)
		os.Exit(1)
	}
	latestDirectCSIDriveInterface, err := directcsiclient.DirectCSIDriveInterfaceForConfig(kubeConfig)
	if err != nil {
		fmt.Printf("%s: could not initialize drive adapter client: err=%v\n", "Error", err)
		os.Exit(1)
	}
	result, err := latestDirectCSIDriveInterface.List(context.Background(), metav1.ListOptions{})
	if err != nil {
		fmt.Printf("could not list drives: %v", err)
		os.Exit(1)
	}

	for _, item := range result.Items {
		fmt.Printf("\n Type: %T", item)
		fmt.Printf("\n drive.Name: %s", item.Name)
		fmt.Printf("\n drive.Path: %s", item.Status.Path)
	}
}
```

Add the following to the go.mod (replace) :-

```go
replace github.com/minio/directpv => ../directpv
```

After merging, you can choose the commit-id from master

```go
require (
    github.com/minio/directpv <commit-id>
)
```

**Comment by bexsoft** [comment]
Incompatibility issue solved. will implement this in Operator API, Thank you very much!

**Review by bexsoft — DISMISSED** [review]
LGTM, I was able to implement calls. Thank you!

**Review by bexsoft — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
merging this as it was already approved by @sinhaashish

**Pull request merged**
