### PR TITLE
Add volume scheduling documentation

### LINKED ISSUE #318: Document volume scheduling (ref: https://github.com/minio/direct-csi/issues/317)
Specifically explain how kubernetes and direct-csi work together to schedule volumes on nodes. Implications of `WaitForFirstConsumer` and topology constraints. 

Also explain how to restrict scheduling to particular nodes

### PR DESCRIPTION
**Pull request by balamurugana**
Fixes #318

### CODE REVIEW

**Comment by Praveenrajmani** [comment]
Do we need a "trouble shooting" section for volume scheduling issues? Like, for eg, if they see issues like "no drive found for requested topology" in the respective pods, we can convey that the the node isn't added (or) the requested size is more etc

**Comment by ravindk89** [comment]
> Do we need a "trouble shooting" section for volume scheduling issues? Like, for eg, if they see issues like "no drive found for requested topology" in the respective pods, we can convey that the the node isn't added (or) the requested size is more etc

It's not a bad idea, but that also largely depends on how common and predictable certain errors are - and how much work it is to maintain that.

But maybe a handful of the most likely suspects (No drives on the node where the pod is scheduled is a good one).
If we go that route though I'd argue we need error codes, not just error messages, to make it easier to do lookups. Otherwise you do string-type matches which can change over time.

**Comment by balamurugana** [comment]
I am thinking docs restructure like below

* installation
  * plugin
    * krew users
    * direct binary users
  * DirectPV
    * default installation
    * customized installation
      * KUBELET_DIR_PATH env var
      * node selector
      * tolerations

* upgrade existing installation
  * plugin
  * DirectPV
    * from v4.x.x
    * from v3.x.x
    * from v2.x.x

* usage guide
  * Add/List/Update/Delete drives
  * Add/List/Update/Delete volumes

* troubleshooting
  * installation issues
    * plugin
    * DirectPV
  * upgrade issues
    * plugin
    * DirectPV
  * Add/List/Update/Delete drives issues
  * Add/List/Update/Delete volumes issues

* architecture
  * plugin
  * DirectPV

* developer guide

I think we would need to address many things than patching this PR

**Comment by djwfyi** [comment]
That doc structure seems reasonable to me, @Praveenrajmani . It covers the major types of docs users would need.

**Comment by Praveenrajmani** [comment]
Can we take this PR and work on the other changes on top? @ravindk89 @djwfyi

**Review by Praveenrajmani — APPROVED** [review]
IMO, We can take this in and restructure the docs later

**Comment by ravindk89** [comment]
Entirely reasonable approach. Go for it

**Pull request merged**
